### PR TITLE
Fix #225: Gun sounds played at weapon instead of player

### LINKED ISSUE #225: 3D Gun Audio Reaches "Uncanny Valley"
Greetings.

I have discovered that while firing weapons it seems to take a "3D" effect and favors the right audio channel. I am unsure if this is intentional, but it seems to give off the "Uncanny Valley" type feeling while shooting. Mainly that it feels... wrong. Mainly as it leaves the left audio channel feel underused, or at worst gives a muted impression.

This effect is made worse if wearing a headset with the ability to hot-switch between 7.1 Surround Sound. (I personally have a HyperX headset and with 7.1 Surround Sound disabled it makes the jarring effect more apparent.)

Has anyone else had this feeling about the gun sound effects?

### PR DESCRIPTION
**Pull request by the-remeko**
Client weapon sounds are played at the weapon world position, instead of the player's eye position or view model position. Thus, the weirdness of shoot sounds can vary wildly depending on whether the player is flicking their mouse, moving, or crouched. If the player shoots while standing still, the sound is louder on the right.

This problem doesn't exist in the Sandbox gamemode because weapon sounds there are played on the player, not the weapon.

I made the game play carriable sounds from the carriable's owner if there is one. ~~and I made it send the sound attached to the weapon to anyone that isn't the currently predicted player (in case Carriable.PlaySound is called from the server). I also made it play at 90% volume for the local player because it sounded far louder than it did for my second client right next to me.~~

### CODE REVIEW

File: code/Items/Base/Carriable.cs [hunk 1]
```diff
@@ -176,6 +176,15 @@ public virtual void OnCarryDrop( Player dropper )
...
 	}
 
+	public override Sound PlaySound( string soundName, string attachment )
+	{
+		if ( Host.IsClient )
+			return Local.Pawn.PlaySound( soundName )
+				.SetVolume( 0.9f );
+
+		return Sound.FromEntity( To.Multiple( Client.All.Where( x => x != Prediction.CurrentHost ) ), soundName, this );
+	}
```
Comment (kolexxx) [inline code/Items/Base/Carriable.cs:186]: Can't we just do `Sound.FromEntity( sound, Owner` ?

Comment (the-remeko) [reply code/Items/Base/Carriable.cs:186]: We can. Would you prefer that over playing the sound at the weapon for other players?

Comment (kolexxx) [reply code/Items/Base/Carriable.cs:186]: Yeah, replace the `PlaySound` call in `AttackPrimary` with `Sound.FromWorld( sound, Owner.EyePosition)`, or somehow override the `PlaySound`.

**Review by matekdev — APPROVED** [review]

File: code/Items/Base/Carriable.cs [hunk 2]
```diff
@@ -176,6 +176,14 @@ public virtual void OnCarryDrop( Player dropper )
 		TimeSinceDropped = 0;
 	}
 
+	public override Sound PlaySound( string soundName, string attachment )
+	{
+		if ( Owner.IsValid() )
+			return Owner.PlaySound( soundName, attachment );
+
+		return base.PlaySound( soundName, attachment );
```
Comment (kolexxx) [inline code/Items/Base/Carriable.cs:184]: This should only be `return Sound.FromWorld( sound, Owner.EyePosition )`.

Comment (the-remeko) [reply code/Items/Base/Carriable.cs:184]: It appears to use EyePosition already when playing sounds on the player. Also, using Sound.FromWorld prevents the sound from following the shooter, which is especially noticeable for the shooter while moving.

Carriables can be dropped on the ground. Without the other return, telling the carriable to play a sound would result in no sound being played.

**Comment by kolexxx** [comment]
Thank you for the bug fix
